name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Orbiter
        uses: orbiterhost/orbiter-github-actions@v0.1.0 # Update with latest version
        with:
          project-name: "polluterofminds" # Name of your project
          build-dir: "./dist" # Name of the build output directory
          api-key: ${{ secrets.ORBITER_API_KEY }} # Will use repository secret
          # Optional inputs with their defaults
          node-version: "20.x" # Optional, defaults to '20.x'
          build-command: "npm run build" # Optional, defaults to 'npm run build'
